### ISSUE TITLE
MySQLとの接続が切れて落ちる問題

### ISSUE THREAD

**Issue by uhey22e** [Canchu/CoffeeManager#44]
Error: Connection lost: The server closed the connection.

**Comment by uhey22e** [comment]
error when connecting to db: { [Error: Cannot enqueue Handshake after fatal error.] code: 'PROTOCOL_ENQUEUE_AFTER_FATAL_ERROR', fatal: false }
213119 DB connected ID:  73
213120 /home/uhey/CoffeeManager/manager/routes/coffeeMarathon.js:34
213121             if (err) throw err;
213122                      ^
213123
213124 Error: Cannot enqueue Query after fatal error.
213125     at Protocol._validateEnqueue (/home/uhey/CoffeeManager/manager/node_modules/mysql/lib/protocol/Protocol.js:199:16)
213126     at Protocol._enqueue (/home/uhey/CoffeeManager/manager/node_modules/mysql/lib/protocol/Protocol.js:135:13)
213127     at Connection.query (/home/uhey/CoffeeManager/manager/node_modules/mysql/lib/Connection.js:214:25)
213128     at async.waterfall.connection.query.async.map.sql (/home/uhey/CoffeeManager/manager/routes/coffeeMarathon.js:33:22)
213129     at nextTask (/home/uhey/CoffeeManager/manager/node_modules/async/dist/async.js:6627:18)
213130     at Object.waterfall (/home/uhey/CoffeeManager/manager/node_modules/async/dist/async.js:6630:9)
213131     at async.parallel.async.waterfall.connection.query.async.map.connection.query.async.waterfall.sql (/home/uhey/CoffeeManager/manager/routes/coffeeMarathon.js:29:13)
213132     at /home/uhey/CoffeeManager/manager/node_modules/async/dist/async.js:5285:13
213133     at replenish (/home/uhey/CoffeeManager/manager/node_modules/async/dist/async.js:871:21)
213134     at /home/uhey/CoffeeManager/manager/node_modules/async/dist/async.js:881:15
213135 error: Forever detected script exited with code: 1
213136 error: Script restart attempt #1
213137 DB connected ID:  80
213138 ^[[0mGET /coffeeMarathon ^[[32m200 ^[[0m2235.323 ms - 2473^[[0m
